modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Alan72104/ArmorStandShiftSwap/issues"
license = "LGPL-3.0-only"

[[mods]]
modId = "armorstandshiftswap"
version = "${version}"
displayName = "Armor Stand Shift Swap"
authors = "Alan72104"
description = '''
Shift right click an armor stand to swap your whole armor set
'''
logoFile = "assets/armorstandshiftswap/icon.png"

[[dependencies.armorstandshiftswap]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armorstandshiftswap]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armorstandshiftswap]]
modId = "architectury"
mandatory = true
versionRange = "[4.12.92,)"
ordering = "AFTER"
side = "BOTH"
